In [36]:
from pathlib import Path
import zipfile
import pandas as pd
import numpy as np

In [37]:
meta_data = pd.read_csv(r"D:\arc\Python\Python Projects\meta_data.csv")
meta_data.head()

   Field Name    Description  Unnamed: 2
0        Year           Year         NaN
1     Quarter  Quarter (1-4)         NaN
2       Month          Month         NaN
3  DayofMonth   Day of Month         NaN
4   DayOfWeek    Day of Week         NaN

In [38]:
df = pd.read_csv(r"d:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\January\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv")

C:\Users\asus\AppData\Local\Temp\ipykernel_2624\1211796770.py:1: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport, 3: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"d:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\January\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv")

In [39]:
raw_data = pd.DataFrame({
    "Field Name" : df.columns,
    "Data_Types": df.dtypes
})

raw_data.head()

            Field Name Data_Types
Year              Year      int64
Quarter        Quarter      int64
Month            Month      int64
DayofMonth  DayofMonth      int64
DayOfWeek    DayOfWeek      int64

In [41]:
set(raw_data["Field Name"]) - set(meta_data['Field Name'])

{'Div4LongestGTime',
 'Div4TailNum',
 'Div4WheelsOff',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5LongestGTime',
 'Div5TailNum',
 'Div5TotalGTime',
 'Div5WheelsOff',
 'Div5WheelsOn',
 'Flight_Number_Reporting_Airline',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'Tail_Number',
 'Unnamed: 109'}

In [43]:
data_dictionary = raw_data.merge(
    meta_data,
    on = "Field Name",
    how = "left"
)

In [44]:
data_dictionary

           Field Name Data_Types    Description  Unnamed: 2
0                Year      int64           Year         NaN
1             Quarter      int64  Quarter (1-4)         NaN
2               Month      int64          Month         NaN
3          DayofMonth      int64   Day of Month         NaN
4           DayOfWeek      int64    Day of Week         NaN
..                ...        ...            ...         ...
124    Div5TotalGTime    float64            NaN         NaN
125  Div5LongestGTime    float64            NaN         NaN
126     Div5WheelsOff    float64            NaN         NaN
127       Div5TailNum    float64            NaN         NaN
128      Unnamed: 109    float64            NaN         NaN

[129 rows x 4 columns]

In [45]:
PROJECT_PATH = Path.cwd().parent
DOCUMENTATION_PATH = PROJECT_PATH / "02_Documentation"

In [48]:
data_dictionary.to_excel(
    DOCUMENTATION_PATH / "data_dictonary.xlsx",
    index = False
)

print("Data Dictionary Saved Successfully")

Data Dictionary Saved Successfully