In [1]:
from pathlib import Path
import zipfile
import numpy as np
import pandas as pd

In [2]:
PROJECT_PATH = Path.cwd().parent
print("Project Path", PROJECT_PATH.resolve())

RAW_PATH = PROJECT_PATH / "01_Raw_Data"
RAW_PATH.mkdir(parents=True, exist_ok=True)
print("Raw_Path", RAW_PATH.resolve())
DOCUMENTATION_PATH = PROJECT_PATH / "02_Documentation"
print("Documentation_Path", DOCUMENTATION_PATH.resolve())

Project Path D:\arc\Python\Python Projects\airline_operations_analytics
Raw_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data
Documentation_Path D:\arc\Python\Python Projects\airline_operations_analytics\02_Documentation

In [3]:
RAW_2024_PATH = RAW_PATH / "2024"
print("Raw_2024_Path", RAW_2024_PATH.resolve())

EXTRACT_PATH = RAW_2024_PATH / "January"
print("Extract_Path", EXTRACT_PATH.resolve())

Raw_2024_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024
Extract_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\January

In [4]:
csv_files = list(EXTRACT_PATH.rglob("*.csv"))
csv_file = csv_files[0]

print(csv_file.name)

On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv

In [5]:
df = pd.read_csv(csv_file,
                 low_memory=False)

In [6]:
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2024,1,1,8,1,2024-01-08,9E,20363,9E,N485PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,9,2,2024-01-09,9E,20363,9E,N912XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,10,3,2024-01-10,9E,20363,9E,N918XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,11,4,2024-01-11,9E,20363,9E,N490PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,12,5,2024-01-12,9E,20363,9E,N915XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
dq = pd.DataFrame({
    "Total Rows": len(df),
    "Total Columns": len(df.columns),
    "Missing Count": df.isna().sum(),
    "Missing Percentage": df.isna().mean() * 100
})

dq

                  Total Rows  Total Columns  Missing Count  Missing Percentage
Year                  547271            110              0                 0.0
Quarter               547271            110              0                 0.0
Month                 547271            110              0                 0.0
DayofMonth            547271            110              0                 0.0
DayOfWeek             547271            110              0                 0.0
...                      ...            ...            ...                 ...
Div5TotalGTime        547271            110         547271               100.0
Div5LongestGTime      547271            110         547271               100.0
Div5WheelsOff         547271            110         547271               100.0
Div5TailNum           547271            110         547271               100.0
Unnamed: 109          547271            110         547271               100.0

[110 rows x 4 columns]

In [16]:
print("Full Missing:", (dq["Missing Count"] == len(df)).sum())

print("Partial Missing:", ((dq["Missing Count"] > 0) & (dq["Missing Count"]< len(df))).sum())

print("No Missing:", (dq["Missing Count"] == 0).sum())

Full Missing: 17
Partial Missing: 54
No Missing: 39

In [10]:
data_validity = df[["Cancelled", "Diverted"]].sum()

data_validity

Cancelled    20389.0
Diverted      1512.0
dtype: float64

In [11]:
quality_assessment = pd.DataFrame ({
    "Column_Name": df.columns,
    "Data_Types": df.dtypes.values,
    "Missing_Count": df.isna().sum().values
})

quality_assessment

          Column_Name Data_Types  Missing_Count
0                Year      int64              0
1             Quarter      int64              0
2               Month      int64              0
3          DayofMonth      int64              0
4           DayOfWeek      int64              0
..                ...        ...            ...
105    Div5TotalGTime    float64         547271
106  Div5LongestGTime    float64         547271
107     Div5WheelsOff    float64         547271
108       Div5TailNum    float64         547271
109      Unnamed: 109    float64         547271

[110 rows x 3 columns]

In [12]:
quality_assessment.to_csv(
    DOCUMENTATION_PATH / "data_quality_assessment.csv",
        index = False
)

print("Quality Assessment Saved Successfully")

Quality Assessment Saved Successfully